name: Auxilor

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Auxilor.yml'
  schedule:
    - cron: '0 */6 * * *'

jobs:
  EcoJobs:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoJobs"
      target: "bin/*"
      name: "EcoJobs"
      java: 17
      readonly: true
  EcoPets:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoPets"
      target: "bin/*"
      name: "EcoPets"
      java: 17
      readonly: true
  EcoCrates:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoCrates"
      target: "bin/*"
      name: "EcoCrates"
      java: 17
      readonly: true
  EcoMobs:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoMobs"
      target: "bin/*"
      name: "EcoMobs"
      java: 17
      readonly: true
  EcoEnchants:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoEnchants"
      target: "bin/*"
      name: "EcoEnchants"
      java: 17
      readonly: true
  EcoSkills:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoSkills"
      target: "bin/*"
      name: "EcoSkills"
      java: 17
      readonly: true
  Reforges:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/Reforges"
      target: "bin/*"
      name: "Reforges"
      java: 17
      readonly: true
  Talismans:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/Talismans"
      target: "bin/*"
      name: "Talismans"
      java: 17
      readonly: true
  EcoArmor:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoArmor"
      target: "bin/*"
      name: "EcoArmor"
      java: 17
      readonly: true
  EcoItems:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoItems"
      target: "bin/*"
      name: "EcoItems"
      java: 17
      readonly: true
  StatTrackers:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/StatTrackers"
      target: "bin/*"
      name: "StatTrackers"
      java: 17
      readonly: true
  Boosters:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/Boosters"
      target: "bin/*"
      name: "Boosters"
      java: 17
      readonly: true
  Actions:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/Actions"
      target: "bin/*"
      name: "Actions"
      java: 17
      readonly: true
  EcoQuests:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoQuests"
      target: "bin/*"
      name: "EcoQuests"
      java: 17
      readonly: true
  EcoScrolls:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoScrolls"
      target: "bin/*"
      name: "EcoScrolls"
      java: 17
      readonly: true
  EcoShop:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoShop"
      target: "bin/*"
      name: "EcoShop"
      java: 17
      readonly: true
  EcoBits:
    uses: maiminhdung/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Auxilor/EcoBits"
      target: "bin/*"
      name: "EcoBits"
      java: 17
      readonly: true
